### ISSUE TITLE
Re-enable outline on focusable elements.

### ISSUE THREAD

**Issue by NullVoxPopuli** [tastejs/todomvc-app-css#35]
Not sure why outline was deliberately, removed, hiding the indication of where your keyboard focus is:

https://github.com/tastejs/todomvc-app-css/blob/master/index.css#L37

I've found that in a more accessible TodoMVC implementation, I need to add the following CSS: 

```css
/* this block re-adds the outline, to support keyboard navigation / tabbing */
:focus,
.view label:focus,
.todo-list li .toggle:focus + label,
.toggle-all:focus + label {
  /* !important needed, because todomvc styles deliberately disable the outline */
  outline: #d86f95 solid !important;
}
```
